name: CloudFormation Create
run-name: CloudFormation Create Stack in ${{ github.ref_name }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      aws-role-arn:
        description: Arn of the role to be assumed.
        required: true
        default: arn:aws:iam::637423502513:role/subhamay-github-oidc-role
        type: string
      aws-region:
        description: AWS region where the services will be deployed
        required: true
        default: us-east-1
        type: string
jobs:
  cfn-create:
    name: Create Stack
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
      # To use OIDC
      id-token: write
      
    steps:
      - name: Checkout Code
        id: git-checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials from AWS account
        id: aws-config
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}
          role-session-name: github-aws-terraform-oidc

      - name: List the files in the workspace
        id: list-file
        run: |
          cd ${{ github.workspace }}
          ls -LR

      - name: Create the Stack
        run: |
          aws cloudformation create-stack \
          --stack-name MyS3BucketStack \
          --template-body file://${{ github.workspace }}/cfn/root-stack-template.yaml \
          --capabilities CAPABILITY_NAMED_IAM

